
select * from INSTFLASHY.FLASHCONF
INSERT INTO INSTFLASHY.FLASHCONF
(USUARIO, HMCIP, IPSTG, IPORG, IPDEST, NOMBRE, SERIAL, LPARID, ETHLIN, CMNDST, LPARHMC, CGRPFC, LPARNRO)
VALUES('flashss   ', '192.168.253.234', '192.168.253.169', '192.168.253.93 ', '192.168.253.103', 'Server-9009-41A-SN7866180     ', '7866180 ', '7 ', 'ETHFLASH ', 'CMN09', '07', 'FC_LAB01       ', 1);

INSERT INTO INSTFLASHY.FLASHCONF
(USUARIO, HMCIP, IPSTG, IPORG, IPDEST, NOMBRE, SERIAL, LPARID, ETHLIN, CMNDST, LPARHMC, CGRPFC, LPARNRO)
VALUES('flashss   ', '192.168.253.234', '192.168.253.169', '192.168.253.93 ', '192.168.253.104', 'Server-9009-41A-SN7866180     ', '7866180 ', '8 ', 'ETHFLASH ', 'CMN09', '08', 'FC_LAB01       ', 2);





CREATE TABLE INSTFLASHY.FLASHCONFIG (
	CFGCONTEXT VARCHAR(20) NOT NULL,
    CFGKEY   VARCHAR(50) NOT NULL,
    CFGVALUE VARCHAR(200),
    PRIMARY KEY (CFGCONTEXT, CFGKEY)
);  



INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_1', 'Usuario', 'flashss');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_1', 'Password', 'passw0rd');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_1', 'HMCIP', '192.168.253.234');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_1', 'IPSTG', '192.168.253.169');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_1', 'IPORG', '192.168.253.93');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_1', 'IPDEST', '192.168.253.103');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_1', 'NOMBRE', 'Server-9009-41A-SN7866180');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_1', 'SERIAL', '7866180');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_1', 'LPARID', '7');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_1', 'ETHLIN', 'ETHFLASH');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_1', 'CMNDST', 'CMN09');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_1', 'LPARHMC', '07');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_1', 'CGRPFC', 'FC_LAB01');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_1', 'LPARNRO', '1');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_1', 'IASP', '*YES');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_1', 'IASPDEV', 'IASP1');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_1', 'TAPDEV', 'TAP01');

INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_2', 'Usuario', 'flashss');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_2', 'Password', 'passw0rd');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_2', 'HMCIP', '192.168.253.234');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_2', 'IPSTG', '192.168.253.169');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_2', 'IPORG', '192.168.253.93');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_2', 'IPDEST', '192.168.253.103');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_2', 'NOMBRE', 'Server-9009-41A-SN7866180');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_2', 'SERIAL', '7866180');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_2', 'LPARID', '8');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_2', 'ETHLIN', 'ETHFLASH');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_2', 'CMNDST', 'CMN09');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_2', 'LPARHMC', '08');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_2', 'CGRPFC', 'FC_LAB01');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_2', 'LPARNRO', '2');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_2', 'IASP', '*YES');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_2', 'IASPDEV', 'IASP1');
INSERT INTO INSTFLASHY.FLASHCONFIG VALUES ('OPCION_2', 'TAPDEV', 'TAP01');


SELECT * FROM INSTFLASHY.FLASHCONFIG

DROP MASK INSTFLASHY.MSK_FLASHCONFIG

CREATE MASK INSTFLASHY.MSK_FLASHCONFIG
ON INSTFLASHY.FLASHCONFIG 
FOR COLUMN CFGVALUE RETURN CASE WHEN TRIM(CURRENT_USER) = 'BENJAMID' THEN CFGVALUE ELSE '%$%$%$%$%$%$%$%$%$%$' END


ALTER TABLE INSTFLASHY.FLASHCONFIG ACTIVATE COLUMN ACCESS CONTROL
ALTER TABLE INSTFLASHY.FLASHCONFIG DEACTIVATE COLUMN ACCESS CONTROL

