/*
select * from INSTFLASHY.FLASHCONF
INSERT INTO INSTFLASHY.FLASHCONF
(USUARIO, HMCIP, IPSTG, IPORG, IPDEST, NOMBRE, SERIAL, LPARID, ETHLIN, CMNDST, LPARHMC, CGRPFC, LPARNRO)
VALUES('flashss   ', '192.168.253.234', '192.168.253.169', '192.168.253.93 ', '192.168.253.103', 'Server-9009-41A-SN7866180     ', '7866180 ', '7 ', 'ETHFLASH ', 'CMN09', '07', 'FC_LAB01       ', 1);

INSERT INTO INSTFLASHY.FLASHCONF
(USUARIO, HMCIP, IPSTG, IPORG, IPDEST, NOMBRE, SERIAL, LPARID, ETHLIN, CMNDST, LPARHMC, CGRPFC, LPARNRO)
VALUES('flashss   ', '192.168.253.234', '192.168.253.169', '192.168.253.93 ', '192.168.253.104', 'Server-9009-41A-SN7866180     ', '7866180 ', '8 ', 'ETHFLASH ', 'CMN09', '08', 'FC_LAB01       ', 2);
*/




CREATE TABLE FLASHLIB.FLASHCFG (
	CFGCONTEXT VARCHAR(20) NOT NULL,
    CFGKEY   VARCHAR(50) NOT NULL,
    CFGVALUE VARCHAR(200),
    PRIMARY KEY (CFGCONTEXT, CFGKEY)
);  


DELETE FROM FLASHLIB.FLASHCFG
;
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_1', 'Usuario', 'flashss');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_1', 'Password', 'passw0rd');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_1', 'HMCIP', '192.168.253.234');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_1', 'IPSTG', '192.168.253.169');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_1', 'IPORG', '192.168.253.93');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_1', 'IPDEST', '192.168.253.103');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_1', 'NOMBRE', 'Server-9009-41A-SN7866180');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_1', 'SERIAL', '7866180');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_1', 'LPARID', '7');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_1', 'ETHLIN', 'ETHFLASH');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_1', 'CMNDST', 'CMN09');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_1', 'LPARHMC', '07');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_1', 'CGRPFC', 'FC_LAB01');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_1', 'LPARNRO', '1');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_1', 'IASP', '*YES');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_1', 'IASPDEV', 'IASP1');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_1', 'SAV', '*YES');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_1', 'SAVDEV', 'TAP01');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_1', 'OPTION', '1');

INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_2', 'Usuario', 'flashss');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_2', 'Password', 'passw0rd');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_2', 'HMCIP', '192.168.253.234');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_2', 'IPSTG', '192.168.253.169');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_2', 'IPORG', '192.168.253.93');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_2', 'IPDEST', '192.168.253.103');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_2', 'NOMBRE', 'Server-9009-41A-SN7866180');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_2', 'SERIAL', '7866180');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_2', 'LPARID', '8');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_2', 'ETHLIN', 'ETHFLASH');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_2', 'CMNDST', 'CMN09');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_2', 'LPARHMC', '08');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_2', 'CGRPFC', 'FC_LAB01');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_2', 'LPARNRO', '2');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_2', 'IASP', '*YES');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_2', 'IASPDEV', 'IASP1');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_2', 'SAV', '*YES');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_2', 'SAVDEV', 'TAP01');
INSERT INTO FLASHLIB.FLASHCFG VALUES ('OPCION_2', 'OPTION', '2');


SELECT * FROM FLASHLIB.FLASHCFG

DROP MASK FLASHLIB.MSK_FLASHCFG

CREATE MASK FLASHLIB.MSK_FLASHCFG
ON FLASHLIB.FLASHCFG 
FOR COLUMN CFGVALUE RETURN CASE WHEN TRIM(CURRENT_USER) = 'BENJAMID' THEN CFGVALUE ELSE '%$%$%$%$%$%$%$%$%$%$' END


ALTER TABLE FLASHLIB.FLASHCFG ACTIVATE COLUMN ACCESS CONTROL
ALTER TABLE FLASHLIB.FLASHCFG DEACTIVATE COLUMN ACCESS CONTROL

